/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/NewProjectModal copy.vue')['default']
    CustomInput: typeof import('./src/components/CustomInput.vue')['default']
    CustomSelect: typeof import('./src/components/CustomSelect.vue')['default']
    CustomTextArea: typeof import('./src/components/CustomTextArea.vue')['default']
    NewProjectModal: typeof import('./src/components/NewProjectModal.vue')['default']
    NewTaskModal: typeof import('./src/components/NewTaskModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SortButtons: typeof import('./src/components/SortButtons.vue')['default']
    TasksTables: typeof import('./src/components/TasksTables.vue')['default']
  }
}
