/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CustomInput: typeof import('./src/components/CustomInput.vue')['default']
    CustomSelect: typeof import('./src/components/CustomSelect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SortButtons: typeof import('./src/components/SortButtons.vue')['default']
  }
}
